title: Edward King
tagline: Stories to stay alive 
description: Writer based in Colorado.
baseurl: ""
url: "https://edwardk.ing"

author:
  name: Edward King
  email: edkingwriter@gmail.com

markdown: kramdown
highlighter: rouge

collections:
  stories:
    output: true
    permalink: /stories/:slug/

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - edwardk_ing_instructions.md
